create TABLE USERS (
	id INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	ENABLED INTEGER NOT NULL,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
);

create TABLE AUTHORITIES (
	id INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(45) NOT NULL,
	AUTHORITY VARCHAR(45) NOT NULL,
	CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID)
);

create TABLE  TOKEN (
id INT PRIMARY KEY AUTO_INCREMENT,
identifier VARCHAR(45) NULL,
token TEXT NULL,
PRIMARY KEY (id));
